---
- template: src=sources.list.{{ ansible_distribution }}.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644
  register: apt_sources_list

- apt: update_cache=yes
  when: apt_sources_list|changed

- apt: update_cache=yes cache_valid_time=3600
  when: apt_sources_list|skipped

- name: Config proxy for apt
  template: src=01proxy.j2 dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=0644
  when: apt_proxy is defined
